import 'dotenv/config';
import express from 'express';import cors from 'cors';import Razorpay from 'razorpay';import crypto from 'crypto';import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';import multer from 'multer';import PDFDocument from 'pdfkit';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'..'),data=path.join(root,'data'),uploads=path.join(data,'uploads'),books=path.join(root,'public','books');[data,uploads,books].forEach(x=>fs.mkdirSync(x,{recursive:true}));
const db=path.join(data,'orders.json'),orders=fs.existsSync(db)?JSON.parse(fs.readFileSync(db)):{};const save=()=>fs.writeFileSync(db,JSON.stringify(orders,null,2));
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(root,'public')));const upload=multer({dest:uploads,limits:{fileSize:10*1024*1024}});const rp=process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
app.post('/api/upload-photo',upload.single('photo'),(q,s)=>{if(!q.file)return s.status(400).json({error:'Photo required'});s.json({photoId:q.file.filename})});
app.post('/api/create-order',async(q,s)=>{try{if(!rp)return s.status(503).json({error:'Razorpay is not configured'});const d=q.body,a=Number(d.amount);if(![39900,59900,79900].includes(a))return s.status(400).json({error:'Invalid package'});const o=await rp.orders.create({amount:a,currency:'INR',receipt:'KI'+Date.now(),payment_capture:1});orders[o.id]={id:o.id,status:'created',amount:a,data:d};save();s.json({keyId:process.env.RAZORPAY_KEY_ID,orderId:o.id,amount:o.amount})}catch(e){console.error(e);s.status(500).json({error:'Order creation failed'})}});
app.post('/api/verify-payment',async(q,s)=>{try{const {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderId}=q.body,o=orders[orderId||razorpay_order_id];if(!o)return s.status(404).json({error:'Order not found'});const exp=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');if(!razorpay_signature||exp!==razorpay_signature)return s.status(400).json({error:'Payment verification failed'});o.status='generating';o.paymentId=razorpay_payment_id;save();generate(o.id).catch(e=>{console.error(e);o.status='failed';o.error='Generation failed. Please contact support.';save()});s.json({ok:true,orderId:o.id})}catch(e){s.status(500).json({error:'Verification failed'})}});
app.get('/api/story/:id',(q,s)=>{const o=orders[q.params.id];if(!o)return s.status(404).json({error:'Not found'});s.json({status:o.status,title:o.title,pages:o.pages,pdfUrl:o.pdfUrl,audioUrl:o.audioUrl,error:o.error})});
async function ai(ep,body,headers={}){const r=await fetch('https://api.openai.com/v1/'+ep,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,...headers},body});if(!r.ok)throw Error('OpenAI '+r.status+' '+(await r.text()).slice(0,500));return r}
async function makeStory(d){const prompt=`Create a children's picture book for ${d.childName}, age ${d.age}. Theme: ${d.theme}. Favorite things: ${d.favorite||'none'}. Dedication: ${d.dedication||'none'}. Return ONLY JSON {"title":"...","pages":[{"title":"...","text":"...","imagePrompt":"..."}]}. Exactly 6 pages. Warm simple language. Each image prompt must preserve the uploaded child's recognizable facial identity, proportions, eyes, nose, mouth, hair and skin tone as the same animated character on every page. No text or watermark.`;const r=await ai('responses',JSON.stringify({model:process.env.OPENAI_TEXT_MODEL||'gpt-5.6-luna',input:prompt}));const j=await r.json();return JSON.parse(j.output_text.replace(/^```json\s*/,'').replace(/\s*```$/,''))}
async function makeImage(prompt,photo){const f=new FormData();f.append('model',process.env.OPENAI_IMAGE_MODEL||'gpt-image-2');f.append('prompt',prompt+' Use the uploaded child photo as identity reference. Keep the same recognizable face; animate the child without redesigning facial features.');f.append('size','1024x1024');f.append('image',new Blob([fs.readFileSync(photo)]),'child.jpg');const r=await ai('images/edits',f),j=await r.json();return Buffer.from(j.data[0].b64_json,'base64')}
async function makeAudio(text){const r=await ai('audio/speech',JSON.stringify({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:'alloy',input:text,format:'mp3'}),{'Content-Type':'application/json'});return Buffer.from(await r.arrayBuffer())}
function makePdf(id,st,imgs){return new Promise((resolve,reject)=>{const f=path.join(books,id+'.pdf'),d=new PDFDocument({size:'A4',margin:40}),w=fs.createWriteStream(f);w.on('finish',()=>resolve('/books/'+id+'.pdf'));w.on('error',reject);d.pipe(w);d.fontSize(30).text(st.title,{align:'center'});st.pages.forEach((p,i)=>{d.addPage();d.fontSize(24).text(p.title,{align:'center'}).moveDown();d.image(imgs[i],{fit:[500,500],align:'center'}).moveDown();d.fontSize(15).text(p.text)});d.end()})}
async function generate(id){if(!process.env.OPENAI_API_KEY)throw Error('OPENAI_API_KEY missing');const o=orders[id],st=await makeStory(o.data),photo=path.join(uploads,o.data.photoId),imgs=[],pages=[];for(let i=0;i<st.pages.length;i++){const b=await makeImage(st.pages[i].imagePrompt,photo),f=path.join(books,`${id}-${i+1}.png`);fs.writeFileSync(f,b);imgs.push(f);pages.push({...st.pages[i],imageUrl:`/books/${id}-${i+1}.png`})}o.title=st.title;o.pages=pages;o.pdfUrl=await makePdf(id,st,imgs);if(o.amount>=59900){const b=await makeAudio(st.pages.map(p=>p.text).join(' ')),f=path.join(books,id+'.mp3');fs.writeFileSync(f,b);o.audioUrl='/books/'+id+'.mp3'}o.status='ready';save()}
app.listen(process.env.PORT||3000,()=>console.log('KidsImagination running'));